<?php
echo '<!DOCTYPE html>';
echo '<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->';
echo '<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->';
echo '<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->';
echo '<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->';
echo '<html>';
echo '<head>';
echo '<meta charset="utf-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<title>Moving Block With Keyboard Keys</title>';
echo '<meta name="description" content="">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1">';
echo '<style>';
echo '.countdown-timer {';
echo 'display: flex;';
echo 'justify-content: center;';
echo 'align-items: center;';
echo 'height: 100%;';
echo 'width: 100%;';
echo '}';
echo '';
echo '.timer-wrapper {';
echo 'display: flex;';
echo 'justify-content: center;';
echo 'align-items: center;';
echo '}';
echo '';
echo '.timer-item {';
echo 'margin: 0 15px;';
echo 'text-align: center;';
echo 'font-size: 32px;';
echo '}';
echo '';
echo '.timer-value {';
echo 'display: inline-block;';
echo 'width: 80px;';
echo 'height: 80px;';
echo 'border-radius: 50%;';
echo 'background-color: #343a40;';
echo 'color: #fff;';
echo 'font-size: 32px;';
echo 'line-height: 80px;';
echo 'text-align: center;';
echo 'animation: timer-animation 1s ease-in-out forwards;';
echo '}';
echo '';
echo '.timer-label {';
echo 'margin-top: 10px;';
echo 'font-size: 18px;';
echo 'font-weight: 600;';
echo 'text-transform: uppercase;';
echo 'color: #343a40;';
echo '}';
echo '';
echo '@keyframes timer-animation {';
echo 'from {';
echo 'transform: scale(1);';
echo '}';
echo 'to {';
echo 'transform: scale(0.8);';
echo '}';
echo '}';
echo '</style>';
echo '<script>';
echo 'const countdownTimer = (deadline) => {';
echo 'const timerHours = document.querySelector('.hours .timer-value');';
echo 'const timerMinutes = document.querySelector('.minutes .timer-value');';
echo 'const timerSeconds = document.querySelector('.seconds .timer-value');';
echo '';
echo 'const startTime = new Date().getTime() + (13 * 60 * 60 + 20 * 60 + 30) * 1000;';
echo '';
echo 'const interval = setInterval(() => {';
echo 'const now = new Date().getTime();';
echo 'const timeLeft = startTime - now;';
echo '';
echo 'if (timeLeft < 0) {';
echo 'clearInterval(interval);';
echo 'return;';
echo '}';
echo '';
echo 'const hours = Math.floor((timeLeft / (1000 * 60 * 60)) % 24);';
echo 'const minutes = Math.floor((timeLeft / (1000 * 60)) % 60);';
echo 'const seconds = Math.floor((timeLeft / 1000) % 60);';
echo '';
echo 'timerHours.textContent = hours < 10 ? '0' + hours : hours;';
echo 'timerMinutes.textContent = minutes < 10 ? '0' + minutes : minutes;';
echo 'timerSeconds.textContent = seconds < 10 ? '0' + seconds : seconds;';
echo '}, 1000);';
echo '}';
echo '';
echo '// Call the function with a deadline of your choice';
echo 'countdownTimer(new Date().getTime());';
echo '</script>';
echo '</head>';
echo '<body>';
echo '<!--[if lt IE 7]>';
echo '<p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>';
echo '<![endif]-->';
echo '<div class="countdown-timer">';
echo '<div class="timer-wrapper">';
echo '<div class="timer-item hours">';
echo '<div class="timer-value"></div>';
echo '<div class="timer-label">Hours</div>';
echo '</div>';
echo '<div class="timer-item minutes">';
echo '<div class="timer-value"></div>';
echo '<div class="timer-label">Minutes</div>';
echo '</div>';
echo '<div class="timer-item seconds">';
echo '<div class="timer-value"></div>';
echo '<div class="timer-label">Seconds</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<a href="https://www.apkcroc.com">apk croc</a>';
echo '</body>';
echo '</html>';
?>
